# Generated by Django 5.2.5 on 2025-09-04 10:30

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('max_brain_trees', models.PositiveIntegerField(default=1)),
                ('max_depth', models.PositiveIntegerField(default=4)),
                ('max_width', models.PositiveIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrainBlockNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('common', '공통'), ('domain', '도메인'), ('ai', 'AI 생성형')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='questionnaire.brainblocknode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrainNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brainnodes', to='questionnaire.brainblocknode')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='questionnaire.brainnode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrainTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled BrainTree', max_length=120)),
                ('domain', models.CharField(choices=[('marketing', 'Marketing'), ('content_creation', 'Content Creation'), ('efficiency', 'Efficiency'), ('business_growth', 'Business Growth'), ('common', 'Common')], max_length=40)),
                ('persona', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=12)),
                ('current_depth', models.PositiveIntegerField(default=1)),
                ('node_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brain_trees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='brainblocknode',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='questionnaire.braintree'),
        ),
        migrations.CreateModel(
            name='PromptArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('prompt_input', models.TextField()),
                ('output_summary', models.TextField(blank=True, default='')),
                ('output_raw', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='questionnaire.brainnode')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='질문 아직없음', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_description', models.TextField(blank=True, default='설명이 아직 없습니다.')),
                ('question_hint', models.CharField(blank=True, default='힌트 없음', max_length=255)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_set', to='questionnaire.brainblocknode')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.category')),
            ],
            options={
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('inherited_context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.brainblocknode')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.question')),
            ],
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='questionnaire.policyplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='braintree',
            index=models.Index(fields=['user', 'status'], name='questionnai_user_id_11178c_idx'),
        ),
        migrations.AddIndex(
            model_name='braintree',
            index=models.Index(fields=['domain'], name='questionnai_domain_f38e0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promptartifact',
            unique_together={('node', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('category', 'order')},
        ),
    ]
