# Generated by Django 5.2.5 on 2025-09-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_rename_question_answer_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brainnode',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='brainnode',
            old_name='question',
            new_name='question_text',
        ),
    ]
