# Generated by Django 5.2.5 on 2025-09-05 10:26

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_rename_answer_brainnode_answer_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='braintree',
            name='questionnai_user_id_11178c_idx',
        ),
        migrations.RemoveIndex(
            model_name='braintree',
            name='questionnai_domain_f38e0f_idx',
        ),
        migrations.RenameField(
            model_name='brainblocknode',
            old_name='tree',
            new_name='braintree',
        ),
        migrations.RemoveField(
            model_name='brainblocknode',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='brainblocknode',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='brainblocknode',
            name='path',
        ),
        migrations.RemoveField(
            model_name='braintree',
            name='current_depth',
        ),
        migrations.RemoveField(
            model_name='braintree',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='braintree',
            name='node_count',
        ),
        migrations.RemoveField(
            model_name='braintree',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='braintree',
            name='status',
        ),
        migrations.RemoveField(
            model_name='braintree',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='brainblocknode',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brainblocknode',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brainblocknode',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS questionnaire_brainblocknode_tree_id_d073f00f;",
            reverse_sql="",
        ),
        migrations.AddField(
            model_name='brainblocknode',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brainblocknode',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brainblocknode',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='questionnaire.brainblocknode'),
        ),
        migrations.AlterField(
            model_name='brainblocknode',
            name='type',
            field=models.CharField(choices=[('common', '공통'), ('domain', '도메인'), ('ai', 'AI 생성형')], default='common', max_length=20),
        ),
        migrations.AlterField(
            model_name='braintree',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='braintree',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='braintrees', to=settings.AUTH_USER_MODEL),
        ),
    ]
