# Generated by Django 5.2.5 on 2025-09-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_remove_braintree_questionnai_user_id_11178c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='node',
        ),
        migrations.AddField(
            model_name='answer',
            name='brainnode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.brainnode'),
        ),
    ]
