# Generated by Django 5.2.5 on 2025-09-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_remove_answer_node_answer_brainnode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_text',
            new_name='question',
        ),
    ]
