# Generated by Django 5.2.5 on 2025-09-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_rename_question_text_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brainnode',
            name='parent',
        ),
    ]
