# Generated by Django 5.2.5 on 2025-09-11 12:28

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_remove_brainnode_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainnode',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='questionnaire.brainnode'),
        ),
    ]
