# Generated by Django 5.2.5 on 2025-09-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_brainnode_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='purpose',
            field=models.CharField(choices=[('context', '맥락 탐색'), ('motivation', '심리 기반 동기/목표'), ('constraint', '조건/제약'), ('other', '기타')], default='context', max_length=20),
        ),
    ]
