# Generated by Django 5.2.5 on 2026-04-14 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_cache_prompt_results'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRAAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, default='', max_length=64)),
                ('context', models.JSONField(default=dict)),
                ('depth_summary', models.JSONField(default=dict)),
                ('expert_state', models.CharField(blank=True, default='', max_length=64)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('braintree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cra_assets', to='questionnaire.braintree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cra_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'domain'], name='questionnai_user_id_26deb3_idx')],
            },
        ),
    ]
