# Generated by Django 5.2.5 on 2026-04-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_cache_cra_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_blocks', to='questionnaire.brainblocknode')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
