# Generated by Django 5.2.5 on 2026-04-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_user_custom_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainblocknode',
            name='type',
            field=models.CharField(choices=[('common', '공통'), ('domain', '도메인'), ('ai', 'AI 생성형'), ('ai_followup', 'AI 보완 질문'), ('user_custom', '직접 추가')], default='common', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserCustomBlock',
        ),
    ]
