# Generated by Django 5.2.5 on 2026-04-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_replace_usercustomblock_with_brainblocknode_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainblocknode',
            name='type',
            field=models.CharField(choices=[('common', '공통'), ('domain', '도메인'), ('ai', 'AI 생성형'), ('ai_followup', 'AI 보완 질문'), ('user_custom', '직접 추가'), ('brain_dump', '브레인 덤프')], default='common', max_length=20),
        ),
    ]
