# Generated by Django 5.2.5 on 2026-05-11 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_alter_brainblocknode_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(blank=True, max_length=200)),
                ('prompt_a', models.TextField()),
                ('b_system', models.TextField()),
                ('b_task', models.TextField()),
                ('tokens', models.JSONField()),
                ('result_a', models.TextField()),
                ('result_b', models.TextField()),
                ('usage_a', models.JSONField(default=dict)),
                ('usage_b', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perf_test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
