# Generated by Django 5.2.5 on 2026-05-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_perftestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='perftestresult',
            name='flipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perftestresult',
            name='vote',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
