# Generated by Django 5.2.5 on 2026-05-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_perftestresult_flipped_perftestresult_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perftestresult',
            name='flipped',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
