"""
Django settings for animamus_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import importlib.util
import os

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#import os
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 프로덕션에서는 반드시 환경 변수 DJANGO_SECRET_KEY를 설정하세요.
# Docker 등에서 DJANGO_SECRET_KEY= 만 넘어오면 빈 문자열이 되어 기본값이 무시되므로, 비었을 때는 개발용 기본값 사용.
_secret_key = os.environ.get("DJANGO_SECRET_KEY", "").strip()
SECRET_KEY = _secret_key or "django-insecure-local-dev-only-not-for-production"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 호스트/CSRF: 브라우저가 localhost·127.0.0.1·LAN IP 등으로 접속할 때 쿠키 도메인이 달라지면
# "CSRF token from POST incorrect" 가 납니다. 배포 시 환경 변수로 맞추세요.
# Docker 등에서 DJANGO_ALLOWED_HOSTS= 만 넘어오면 빈 문자열이 되어 기본 목록이 무시됨 → 비었을 때는 로컬 기본값 사용
_default_allowed = "localhost,127.0.0.1,0.0.0.0"
_raw_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip() or _default_allowed
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(",") if h.strip()]

# ngrok 터널: DJANGO_ALLOW_NGROK=1 이면 *.ngrok-free.app 등 서브도메인 허용(선행 점 패턴)
# 고정 호스트만 쓸 경우에는 DJANGO_ALLOWED_HOSTS에 호스트명을 직접 넣어도 됨.
if os.environ.get("DJANGO_ALLOW_NGROK", "").strip() in ("1", "true", "True", "yes"):
    for _ng in (".ngrok-free.app", ".ngrok.io", ".ngrok.app"):
        if _ng not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_ng)

# Cloud Run: K_SERVICE 이 있으면 *.run.app 호스트(리전 URL) 허용
if os.environ.get("K_SERVICE") and ".run.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".run.app")

# sagepontus.com 커스텀 도메인 — apex·서브도메인·와일드카드(선행 점) 모두 명시
# (Cloud Run 의 DJANGO_ALLOWED_HOSTS 가 좁게만 잡혀 있어도 아래는 항상 병합됨)
for _h in ("demo.sagepontus.com", "sagepontus.com", ".sagepontus.com"):
    if _h not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_h)

# 로컬 개발: .env에 DJANGO_ALLOWED_HOSTS를 배포 호스트만 넣어도 runserver 접속 가능
if DEBUG:
    for _local in ("127.0.0.1", "localhost", "[::1]"):
        if _local not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_local)

# Django 4+: 비HTTPS도 Referer/Origin 검사에 사용 (포트 포함)
_default_origins = (
    "http://localhost:8000,http://127.0.0.1:8000,"
    "http://[::1]:8000"
)
# Docker 등에서 CSRF_TRUSTED_ORIGINS= 만 넘어오면 빈 문자열이 되어 기본 목록이 무시됨 → 비었을 때는 기본값 사용
_raw_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "").strip() or _default_origins
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_origins.split(",") if o.strip()]
# 커스텀 도메인 데모: CSRF_TRUSTED_ORIGINS 미설정 시 https/http demo 호스트 보강
if not os.environ.get("CSRF_TRUSTED_ORIGINS", "").strip():
    for _demo_origin in (
        "https://demo.sagepontus.com",
        "http://demo.sagepontus.com",
    ):
        if _demo_origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_demo_origin)
# ngrok HTTPS로 접속 시 Origin 이 https://서브도메인.ngrok-free.app 이므로, 와일드카드 불가 → 전체 출처 한 줄
_ngrok_origin = os.environ.get("DJANGO_NGROK_ORIGIN", "").strip()
if _ngrok_origin and _ngrok_origin not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(_ngrok_origin)

# 로컬 개발: CSRF_TRUSTED_ORIGINS를 프로덕션만 넣은 경우에도 127.0.0.1:8000 등 POST 가능
if DEBUG:
    for _origin in (
        "http://127.0.0.1:8000",
        "http://localhost:8000",
        "http://[::1]:8000",
    ):
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)

# 공개 데모 (/demo/): QR·평가용. 프로덕션에서는 DEMO_ENABLED=0 권장.
# Docker 에서 DEMO_ENABLED= 만 넘어오면 빈 문자열 → 아래에서 DEBUG 기본값으로 복구
_demo_flag = os.environ.get("DEMO_ENABLED", "").strip()
if not _demo_flag:
    _demo_flag = "1" if DEBUG else "0"
DEMO_ENABLED = _demo_flag == "1"
DEMO_USER_USERNAME = os.environ.get("DEMO_USER_USERNAME", "demo_gov_evaluator")
# 데모 도메인 선택 화면의 추천 도메인 (DB Category.name 과 일치, 현재는 startup 질문만 시드됨)
DEMO_DOMAIN_CATEGORY = os.environ.get("DEMO_DOMAIN_CATEGORY", "startup")

# questionnaire/prompts/versions/<PROMPT_VERSION>/manifest.yaml
PROMPT_VERSION = os.environ.get("PROMPT_VERSION", "v1")
# Hugging Face Inference API — manifest 의 model 보다 우선(비우면 manifest 사용)
HF_MODEL_ID = os.environ.get("HF_MODEL_ID", "").strip()

# Application definition

INSTALLED_APPS = [
    'adminsortable2',
    'django_extensions',
    'rest_framework',
    'animamus_common',
    'accounts',
    'questionnaire',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]
# Gunicorn/Cloud Run 등에서는 runserver 가 없어 정적 파일이 404 가 됨 → WhiteNoise(Docker 이미지에 포함)
if importlib.util.find_spec("whitenoise"):
    MIDDLEWARE.append("whitenoise.middleware.WhiteNoiseMiddleware")
MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'animamus_project.urls'





TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [],
        'DIRS': [BASE_DIR / 'templates'],
        #'DIRS': [BASE_DIR / 'questionnaire/templates'],
        #'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'questionnaire.context_processors.demo_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'animamus_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Supabase(GCP·Cloud Run): Secret Manager 등에 DATABASE_URL 을 넣고 주입하세요.
# 예: postgresql://postgres.[ref]:[password]@aws-0-[region].pooler.supabase.com:6543/postgres?sslmode=require
# Cloud Run + Transaction pooler(6543)는 conn_max_age=0 권장.

_database_url = os.environ.get("DATABASE_URL", "").strip()
if _database_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=_database_url,
            conn_max_age=0,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ko'  # 기본 언어
USE_I18N = True
USE_L10N = True
LOCALE_PATHS = [BASE_DIR / 'locale']


TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
'''
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'questionnaire/static',
]
'''

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# collectstatic 대상 — Gunicorn+WhiteNoise 가 여기서 서빙
STATIC_ROOT = BASE_DIR / 'staticfiles'






# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
