# Generated by Django 5.2.5 on 2026-05-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyAccessSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('industry', models.CharField(choices=[('physical_therapy', '물리치료 / 재활치료'), ('sports_medicine', '스포츠의학'), ('orthopedics', '정형외과'), ('healthcare_general', '헬스케어 일반'), ('other', '기타')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
