# Generated by Django 5.2.4 on 2025-08-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_answerset_category_prompt_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, help_text='입력 가이드를 위한 설명'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='general', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='guidance',
            field=models.TextField(blank=True, help_text='입력 가이드를 위한 예시'),
        ),
    ]
