# Generated by Django 5.2.4 on 2025-08-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerset',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='promptflow',
            name='next_prompt',
        ),
        migrations.RemoveField(
            model_name='promptflow',
            name='current_prompt',
        ),
        migrations.RemoveField(
            model_name='promptflow',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerSet',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.DeleteModel(
            name='PromptFlow',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
