"""
Referral Letter Generator
Red Flag 알람 → 의사 리퍼럴 레터 자동 생성

근거 기반 작성: 임상 가이드라인 인용, 할루시네이션 배제.
"""

from __future__ import annotations

import logging
from datetime import date

logger = logging.getLogger(__name__)

_CONDITION_META = {
    "cauda_equina": {
        "title":    "Cauda Equina Syndrome (마미총 증후군)",
        "urgency":  "EMERGENCY — Same-day ER referral",
        "guideline":"APTA Clinical Practice Guidelines; Goodman & Snyder Ch.14",
        "action":   "Emergent MRI of lumbar spine; surgical consultation within 48 hours",
    },
    "fracture": {
        "title":    "Suspected Spinal Fracture",
        "urgency":  "URGENT — Imaging prior to any manual therapy",
        "guideline":"APTA Low Back Pain CPG; Goodman & Snyder Ch.14",
        "action":   "Plain radiograph or CT lumbar spine; orthopedic consultation",
    },
    "malignancy": {
        "title":    "Suspected Spinal Malignancy / Metastatic Disease",
        "urgency":  "URGENT — Medical evaluation within 24-48 hours",
        "guideline":"Henschke et al. Screen of 5 CPR; Goodman & Snyder Ch.13",
        "action":   "CBC, ESR, CRP, PSA (if male); MRI lumbar spine; oncology referral if indicated",
    },
    "infection": {
        "title":    "Suspected Spinal Infection (Discitis / Osteomyelitis)",
        "urgency":  "URGENT — Same-day medical evaluation",
        "guideline":"Goodman & Snyder Ch.14; IDSA Spinal Infection Guidelines",
        "action":   "ESR, CRP, WBC, blood cultures; MRI lumbar spine with contrast",
    },
    "vascular": {
        "title":    "Suspected Abdominal Aortic Aneurysm (AAA)",
        "urgency":  "EMERGENCY — Immediate ER if acute pain escalation",
        "guideline":"Goodman & Snyder Ch.6; ACC/AHA AAA Guidelines",
        "action":   "Abdominal ultrasound or CT-A; vascular surgery consultation",
    },
    "inflammatory": {
        "title":    "Suspected Inflammatory Spondyloarthropathy (Ankylosing Spondylitis)",
        "urgency":  "NON-URGENT — Rheumatology referral within 2 weeks",
        "guideline":"ASAS Classification Criteria; Goodman & Snyder Ch.27",
        "action":   "HLA-B27, ESR, CRP; pelvic X-ray; MRI SI joints; rheumatology referral",
    },
    "pathological_fracture": {
        "title":    "Suspected Pathological Fracture (Malignancy + Fracture co-present)",
        "urgency":  "EMERGENCY — Same-day oncology + orthopedic evaluation",
        "guideline":"Goodman & Snyder Ch.13-14; APTA Cancer Rehabilitation CPG",
        "action":   "Urgent MRI spine; oncology + orthopedic co-consult; no manual therapy or weight-bearing until imaging",
    },
}


def generate_referral_letter(
    alert,
    patient_id: str,
    therapist_name: str,
    clinic_name: str = "",
    session_date: date | None = None,
) -> str:
    """
    RedFlagAlert 객체 → 리퍼럴 레터 텍스트 생성.

    Args:
        alert:          RedFlagAlert 인스턴스
        patient_id:     익명 환자 ID
        therapist_name: 치료사 이름
        clinic_name:    클리닉/센터 이름 (선택)
        session_date:   세션 날짜 (없으면 오늘)
    """
    meta = _CONDITION_META.get(alert.condition, {
        "title":    alert.condition,
        "urgency":  "Medical evaluation recommended",
        "guideline":"Clinical judgment",
        "action":   "Physician evaluation",
    })

    today = (session_date or date.today()).strftime("%B %d, %Y")
    clinic_line = f"{clinic_name}\n" if clinic_name else ""
    indicators_str = "\n".join(f"  • {label}" for label in alert.matched_indicators)
    trigger_line = (
        f"\nPrimary trigger: {alert.trigger_label}\n"
        if alert.trigger_label else ""
    )

    letter = f"""
================================================================================
PHYSICAL THERAPY — PHYSICIAN REFERRAL LETTER
================================================================================
Date:      {today}
From:      {therapist_name}
{clinic_line}Patient:   {patient_id} (anonymous ID — PHI withheld per HIPAA)
Re:        Clinical Red Flag Alert — {meta['title']}
================================================================================

Dear Physician,

I am writing to refer the above patient for urgent medical evaluation following
identification of clinical red flag indicators during physical therapy assessment.

ALERT LEVEL: {alert.alarm_level}
SUSPECTED CONDITION: {meta['title']}
URGENCY: {meta['urgency']}

OBSERVED CLINICAL INDICATORS:
{indicators_str}{trigger_line}
RISK SCORE: {alert.score:.2f} / 1.00

CLINICAL BASIS:
This referral is generated per evidence-based guidelines:
{meta['guideline']}

RECOMMENDED EVALUATION:
{meta['action']}

IMPORTANT: Physical therapy treatment has been suspended pending medical
clearance. This patient should not receive spinal manipulation or progressive
loading exercises until the above conditions have been ruled out.

This referral was generated by Sage Pontus PT Red Flag Screening System,
based on the Goodman & Snyder Differential Diagnosis framework.

Respectfully,
{therapist_name}
Physical Therapist
{clinic_name}
================================================================================
""".strip()

    return letter


def generate_multi_referral_letter(
    conditions: list[dict],
    patient_id: str,
    therapist_name: str,
    clinic_name: str = "",
    session_date: "date | None" = None,
) -> str:
    """
    멀티 컨디션 리퍼럴 레터 — conditions 리스트 (scorer 반환값) 기반.

    Args:
        conditions: detect_red_flags()["conditions"] 리스트
        patient_id, therapist_name, clinic_name, session_date: 기존과 동일
    """
    from datetime import date as _date
    today = (session_date or _date.today()).strftime("%B %d, %Y")
    clinic_line = f"{clinic_name}\n" if clinic_name else ""

    # NONE 제외하고 RED 우선 정렬
    active = [c for c in conditions if c.get("alarm", "NONE") != "NONE"]
    if not active:
        return ""

    # 리퍼럴 대상 섹션 빌드
    condition_sections = []
    for c in active:
        cond_id = c["condition"]
        meta = _CONDITION_META.get(cond_id, {
            "title":    cond_id.replace("_", " ").title(),
            "urgency":  "Medical evaluation recommended",
            "guideline":"Clinical judgment",
            "action":   "Physician evaluation",
        })
        indicators_str = "\n".join(f"  • {m}" for m in c.get("matched", []))
        trigger_line = f"\n  Primary trigger: {c['trigger']}\n" if c.get("trigger") else ""
        section = (
            f"  [{c['alarm']}] {meta['title']}\n"
            f"  Urgency: {meta['urgency']}\n"
            f"  Indicators:\n{indicators_str}{trigger_line}"
            f"  Recommended: {meta['action']}\n"
            f"  Guideline: {meta['guideline']}"
        )
        condition_sections.append(section)

    conditions_body = "\n\n".join(condition_sections)
    top_alarm = active[0]["alarm"]

    letter = f"""
================================================================================
PHYSICAL THERAPY — PHYSICIAN REFERRAL LETTER
================================================================================
Date:      {today}
From:      {therapist_name}
{clinic_line}Patient:   {patient_id} (anonymous ID — PHI withheld per HIPAA)
Re:        Clinical Red Flag Alert — {len(active)} Condition(s) Identified
================================================================================

Dear Physician,

I am writing to refer the above patient for urgent medical evaluation following
identification of clinical red flag indicators during physical therapy assessment.

OVERALL ALERT LEVEL: {top_alarm}

IDENTIFIED CONDITIONS:
--------------------------------------------------------------------------------
{conditions_body}
--------------------------------------------------------------------------------

IMPORTANT: Physical therapy treatment has been suspended pending medical
clearance. This patient should not receive spinal manipulation or progressive
loading exercises until the above conditions have been ruled out.

This referral was generated by Sage Pontus PT Red Flag Screening System,
based on the Goodman & Snyder Differential Diagnosis framework.

Respectfully,
{therapist_name}
Physical Therapist
{clinic_name}
================================================================================
""".strip()

    return letter


def generate_referral_with_ai(alert, patient_id: str, therapist_name: str,
                               soap_text: str, clinic_name: str = "") -> str:
    """AI 강화 리퍼럴 레터 — SOAP 내용 기반 더 구체적인 서술."""
    try:
        from questionnaire.prompts.service import _chat_generate

        base = generate_referral_letter(alert, patient_id, therapist_name, clinic_name)
        prompt = (
            "You are a clinical documentation assistant. "
            "Enhance the following referral letter by incorporating specific clinical "
            "observations from the SOAP note. Do NOT add diagnoses or speculate beyond "
            "what is documented. Keep the letter professional and concise.\n\n"
            f"SOAP NOTE:\n{soap_text}\n\n"
            f"BASE REFERRAL:\n{base}\n\n"
            "Return ONLY the enhanced letter text."
        )
        enhanced = _chat_generate()(
            "gemini-2.5-flash",
            prompt,
            {"max_tokens": 1024, "temperature": 0.2},
        )
        return enhanced.strip()
    except Exception as e:
        logger.warning("AI referral 생성 실패, 기본 레터 반환: %s", e)
        return generate_referral_letter(alert, patient_id, therapist_name, clinic_name)
