"""
Phase 1 리퍼럴 추적 — 이메일 발송 + 상태 관리

설정 필요 (.env):
  EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD
  EMAIL_USE_TLS=True, DEFAULT_FROM_EMAIL
"""

from __future__ import annotations

import logging
from datetime import date, timedelta

from django.core.mail import send_mail
from django.conf import settings
from django.utils import timezone

logger = logging.getLogger(__name__)

_REFERRAL_SUBJECT = "Physical Therapy Referral — Urgent Clinical Concern"

_REFERRAL_BODY_TEMPLATE = """\
{letter}

---
This referral was generated by the SagePontus PT Red Flag Monitoring System.
Please contact the referring therapist if you have any questions.
"""

_REMINDER_SUBJECT = "PT Referral Follow-up Reminder — 30 Days Elapsed"

_REMINDER_BODY_TEMPLATE = """\
Dear {therapist_name},

A referral letter was sent for patient {patient_id} on {sent_date}.
It has been 30 days and follow-up has not yet been confirmed.

Please log in to SagePontus to confirm whether the patient followed up with the physician.

Patient:    {patient_id}
Condition:  {condition}
Alarm:      {alarm_level}
Sent to:    {sent_to}

Please mark the follow-up status in the PT app.

— SagePontus Reminder System
"""


def send_referral_email(alert, to_email: str, therapist_name: str = "") -> bool:
    """
    리퍼럴 레터를 의사 이메일로 발송.
    성공 시 alert.referral_sent_at, referral_sent_to_email, referral_email_delivered 업데이트.
    반환: 발송 성공 여부
    """
    if not alert.referral_letter:
        logger.warning("referral_letter 없음 — alert_id=%s", alert.id)
        return False

    from_email = getattr(settings, "DEFAULT_FROM_EMAIL", "noreply@sagepontus.com")
    body = _REFERRAL_BODY_TEMPLATE.format(letter=alert.referral_letter)

    try:
        send_mail(
            subject=_REFERRAL_SUBJECT,
            message=body,
            from_email=from_email,
            recipient_list=[to_email],
            fail_silently=False,
        )
        delivered = True
    except Exception as e:
        logger.warning("리퍼럴 이메일 발송 실패 (alert=%s): %s", alert.id, e)
        delivered = False

    now = timezone.now()
    alert.referral_sent_at       = now
    alert.referral_sent_to_email = to_email
    alert.referral_email_delivered = delivered
    alert.save(update_fields=["referral_sent_at", "referral_sent_to_email", "referral_email_delivered"])
    return delivered


def mark_sent(alert, to_email: str = "") -> None:
    """PT가 수동으로 '보냈음' 체크 (이메일 없이도 상태 기록)."""
    now = timezone.now()
    update_fields = ["referral_sent_at"]
    alert.referral_sent_at = now
    if to_email:
        alert.referral_sent_to_email = to_email
        update_fields.append("referral_sent_to_email")
    alert.save(update_fields=update_fields)


def mark_followup(alert) -> None:
    """PT가 '환자 follow-up 확인' 체크."""
    now = timezone.now()
    alert.referral_followup_checked = True
    alert.referral_followup_at      = now
    alert.save(update_fields=["referral_followup_checked", "referral_followup_at"])


def find_overdue_alerts(days: int = 30):
    """
    발송 후 N일 경과했지만 follow-up 미확인 alert 목록 반환.
    management command에서 사용.
    """
    from vertical_pt.models import RedFlagAlert

    cutoff = timezone.now() - timedelta(days=days)
    return (
        RedFlagAlert.objects
        .filter(
            referral_sent_at__lte=cutoff,
            referral_followup_checked=False,
        )
        .select_related("timeline", "timeline__therapist")
    )


def send_followup_reminder(alert) -> bool:
    """PT(therapist)에게 follow-up 리마인더 이메일 발송."""
    therapist = alert.timeline.therapist
    to_email  = therapist.email
    if not to_email:
        logger.warning("therapist 이메일 없음 — user=%s", therapist.username)
        return False

    from_email = getattr(settings, "DEFAULT_FROM_EMAIL", "noreply@sagepontus.com")
    body = _REMINDER_BODY_TEMPLATE.format(
        therapist_name=therapist.get_full_name() or therapist.username,
        patient_id=alert.timeline.patient_id,
        sent_date=alert.referral_sent_at.strftime("%Y-%m-%d") if alert.referral_sent_at else "unknown",
        condition=alert.condition,
        alarm_level=alert.alarm_level,
        sent_to=alert.referral_sent_to_email or "—",
    )

    try:
        send_mail(
            subject=_REMINDER_SUBJECT,
            message=body,
            from_email=from_email,
            recipient_list=[to_email],
            fail_silently=False,
        )
        logger.info("Follow-up 리마인더 발송 → %s (alert=%s)", to_email, alert.id)
        return True
    except Exception as e:
        logger.warning("리마인더 발송 실패 (alert=%s): %s", alert.id, e)
        return False
