# Generated by Django 5.2.5 on 2026-05-17 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('session_date', models.DateField()),
                ('soap_text', models.TextField()),
                ('extracted_symptoms', models.JSONField(default=dict)),
                ('critical_score', models.FloatField(default=0.0)),
                ('alarm_level', models.CharField(choices=[('RED', 'Red — 즉시 리퍼럴'), ('YELLOW', 'Yellow — 주의 관찰'), ('NONE', 'None — 정상')], default='NONE', max_length=10)),
                ('triggered_condition', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_timelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['patient_id', 'session_date'],
            },
        ),
        migrations.CreateModel(
            name='RedFlagAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50)),
                ('alarm_level', models.CharField(choices=[('RED', 'Red — 즉시 리퍼럴'), ('YELLOW', 'Yellow — 주의 관찰')], max_length=10)),
                ('matched_indicators', models.JSONField(default=list)),
                ('score', models.FloatField(default=0.0)),
                ('trigger_label', models.CharField(blank=True, max_length=200)),
                ('referral_letter', models.TextField(blank=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vertical_pt.patienttimeline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_id', models.CharField(db_index=True, max_length=50)),
                ('symptom_id', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('alarm_level', models.CharField(choices=[('RED', 'Red'), ('YELLOW', 'Yellow')], default='YELLOW', max_length=10)),
                ('condition_ref', models.CharField(max_length=50)),
                ('is_standalone_trigger', models.BooleanField(default=False)),
                ('cluster', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['protocol_id', '-weight'],
                'unique_together': {('protocol_id', 'symptom_id')},
            },
        ),
        migrations.AddIndex(
            model_name='patienttimeline',
            index=models.Index(fields=['therapist', 'patient_id', 'session_date'], name='vertical_pt_therapi_716ba1_idx'),
        ),
    ]
