# Generated by Django 5.2.5 on 2026-05-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical_pt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttimeline',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
