# Generated by Django 5.2.5 on 2026-05-18 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical_pt', '0002_patient_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PT', 'Physical Therapist'), ('PTA', 'PT Assistant'), ('ADMIN', 'Clinic Admin')], default='PT', max_length=10)),
                ('clinic_name', models.CharField(blank=True, max_length=120)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pt_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PT Profile',
            },
        ),
    ]
