# Generated by Django 5.2.5 on 2026-05-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical_pt', '0003_ptprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttimeline',
            name='clinical_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
