# Generated by Django 5.2.5 on 2026-05-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical_pt', '0004_add_clinical_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='redflagalert',
            name='referral_email_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redflagalert',
            name='referral_followup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redflagalert',
            name='referral_followup_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redflagalert',
            name='referral_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redflagalert',
            name='referral_sent_to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
