# Generated by Django 5.2.5 on 2026-05-24 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical_pt', '0005_add_referral_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('soap', 'SOAP 수정'), ('alarm', 'Alarm 결정'), ('document', '문서 수정')], db_index=True, max_length=20)),
                ('original_content', models.TextField(blank=True)),
                ('edited_content', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, choices=[('ADOPTED', '채택'), ('REJECTED', '기각'), ('MODIFIED', '수정 후 채택')], max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('doc_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='vertical_pt.redflagalert')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_pairs', to=settings.AUTH_USER_MODEL)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_pairs', to='vertical_pt.patienttimeline')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['therapist', 'type'], name='vertical_pt_therapi_b8e354_idx'), models.Index(fields=['timeline', 'type'], name='vertical_pt_timelin_0dc321_idx')],
            },
        ),
    ]
