# Generated by Django 5.2.5 on 2026-05-27 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical_pt', '0006_audit_pair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50)),
                ('version', models.CharField(choices=[('template', 'Template'), ('ai', 'AI')], max_length=20)),
                ('content', models.TextField()),
                ('chosen', models.BooleanField(default=False)),
                ('chosen_at', models.DateTimeField(blank=True, null=True)),
                ('generation_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_docs', to=settings.AUTH_USER_MODEL)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_docs', to='vertical_pt.patienttimeline')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['therapist', 'doc_type', 'chosen'], name='gendoc_thera_dtype_chosen')],
            },
        ),
    ]
