# Generated by Django 5.2.5 on 2026-05-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical_pt', '0007_generated_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpair',
            name='section_diffs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
