# Generated by Django 5.2.5 on 2026-05-27 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical_pt', '0008_add_section_diffs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(choices=[('physician', 'Physician'), ('lawyer', 'Lawyer / Attorney'), ('insurance', 'Insurance Company'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'name'],
                'indexes': [models.Index(fields=['therapist', 'patient_id'], name='vertical_pt_therapi_8f84df_idx')],
            },
        ),
    ]
