# Generated by Django 5.2.5 on 2026-05-27 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical_pt', '0009_add_patient_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', '버그'), ('improvement', '개선 제안'), ('praise', '칭찬'), ('question', '질문')], default='improvement', max_length=20)),
                ('message', models.TextField()),
                ('page_url', models.CharField(blank=True, max_length=300)),
                ('patient_id', models.CharField(blank=True, max_length=100)),
                ('doc_type', models.CharField(blank=True, max_length=50)),
                ('action_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
