# Generated by Django 5.2.5 on 2026-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical_pt', '0013_redflagalert_monitoring_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditpair',
            name='decision',
            field=models.CharField(blank=True, choices=[('ADOPTED', '채택'), ('REJECTED', '기각'), ('MODIFIED', '수정 후 채택'), ('MONITORING', 'YELLOW 모니터링 지정')], max_length=20),
        ),
    ]
