# Generated by Django 5.2.5 on 2026-06-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical_pt', '0014_alter_auditpair_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptprofile',
            name='is_early_access',
            field=models.BooleanField(default=False),
        ),
    ]
