# Generated by Django 5.2.5 on 2025-08-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='이 카테고리에 대한 간단한 설명')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(default='general', max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('guidance', models.TextField(blank=True, help_text='입력 가이드를 위한 예시')),
                ('hint', models.TextField(blank=True, help_text='입력 가이드를 위한 설명')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='animamus_common.category')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='animamus_common.responseset')),
            ],
        ),
    ]
